[package]
name = "steam_randomiser"
version = "0.1.0"
authors = ["Dimitri Belopopsky <dimitri@belopopsky.com>"]
edition = "2018"
license = "MIT"
description = "A tool to search files"
readme = "README.md"
homepage = "https://github.com/ShadowMitia/steam_randomiser"
repository = "https://github.com/ShadowMitia/steam_randomiser"
keywords = ["cli", "steam", "random", "game"]
categories = ["command-line-utilities"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "3.0.1"
rand = "0.8.3"
which = "4.1.0"

[profile.release]
lto = true
codegen-units = 1